openapi: 3.0.0
info:
  description: Liber love
  contact:
    email: t_long@stagegroup.jp
  title: liber Love
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /register:
    post:
      summary: ''
      operationId: post-register
      responses:
        '200':
          description: Success
      description: Use register new account user
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                rule:
                  type: boolean
                nick_name:
                  type: string
                birthday:
                  type: string
                  format: date-time
                area:
                  type: string
                city:
                  type: string
                gender_born:
                  type: string
                gender:
                  type: string
                bodies:
                  type: array
                  items:
                    type: string
                personalities:
                  type: array
                  items: {}
                hobbies:
                  type: array
                  items:
                    type: string
                image_id:
                  type: string
                  format: binary
                images:
                  type: string
                  format: binary
                introduction:
                  type: string
                ages_other_person:
                  type: array
                  items:
                    type: string
                areas_other_person:
                  type: array
                  items:
                    type: string
                cities_other_person:
                  type: array
                  items:
                    type: string
                genders_born_other_person:
                  type: array
                  items:
                    type: string
                genders_other_person:
                  type: array
                  items:
                    type: string
                bodies_other_person:
                  type: array
                  items:
                    type: string
                personalities_other_person:
                  type: array
                  items:
                    type: string
            examples:
              example-1:
                value:
                  email: user@example.com
                  password: string
                  rule: true
                  nick_name: string
                  birthday: '2019-08-24T14:15:22Z'
                  area: string
                  city: string
                  gender_born: string
                  gender: string
                  bodies:
                    - string
                  personalities:
                    - null
                  hobbies:
                    - string
                  image_id: string
                  images: string
                  introduction: string
                  ages_other_person:
                    - string
                  areas_other_person:
                    - string
                  cities_other_person:
                    - string
                  genders_born_other_person:
                    - string
                  genders_other_person:
                    - string
                  bodies_other_person:
                    - string
                  personalities_other_person:
                    - string
  /user/profile:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-user
      description: get all info user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                last_name:
                  type: string
                last_time_active:
                  type: string
                nick_name:
                  type: string
                has_free_time:
                  type: boolean
                birthday:
                  type: string
                area:
                  type: string
                city:
                  type: string
                gender_born:
                  type: string
                gender:
                  type: string
                bodies:
                  type: array
                  items:
                    type: string
                personalities:
                  type: array
                  items:
                    type: string
                hobbies:
                  type: array
                  items:
                    type: string
                images:
                  type: array
                  items:
                    type: string
                introduction:
                  type: string
                areas_other_person:
                  type: array
                  items:
                    type: object
                    properties:
                      area:
                        type: string
                      cities:
                        type: array
                        items:
                          type: string
                ages_other_person:
                  type: array
                  items:
                    type: string
                gender_borns_other_person:
                  type: string
                genders_other_person:
                  type: string
                bodies_other_person:
                  type: string
                personalities_other_person:
                  type: array
                  items:
                    type: string
                show_swipe:
                  type: boolean
                show_info:
                  type: boolean
                private_profile:
                  type: boolean
                activity:
                  type: boolean
                push_local:
                  type: object
                  properties:
                    liked:
                      type: boolean
                    matched:
                      type: boolean
                    message:
                      type: boolean
                    other_news:
                      type: boolean
                push_mail:
                  type: object
                  properties:
                    liked:
                      type: boolean
                    matched:
                      type: boolean
                    message:
                      type: boolean
                    other_news:
                      type: boolean
                email:
                  type: string
            examples:
              profile:
                value:
                  email: abc@example.com
                  phone: '0123456789'
                  first_name: 名前
                  last_name: 年齢
                  last_time_active: '10:50 9/9/2020'
                  nick_name: susake
                  has_free_time: true
                  birthday: '2010-02-11'
                  area: 北海道
                  city: 千代田区
                  gender_born: 男
                  gender: どちらでもない
                  bodies:
                    - 男性的
                    - ぽっちゃり
                  personalities:
                    - 優しい
                    - インドア
                  hobbies:
                    - ファッション
                    - 音楽
                    - 映画鑑賞
                    - メイク・美容ケア
                  images:
                    - 'https://ibb.co/XCGnGTb'
                    - 'https://ibb.co/JrqVFcY'
                  introduction: 自己紹介が入ります。自己紹介が入ります。自己紹介が入ります。自己紹介が入ります。自己紹介が入ります。自己紹介が入ります。自己紹介が入ります。自己紹介が入ります。自己紹介が入ります。自己紹介が入ります。自己紹介が入ります。
                  areas_other_person:
                    - area: 北海道
                      cities:
                        - 千代田区
                        - 中央区
                    - area: 秋田
                      cities:
                        - 文京区
                        - 中央区
                  ages_other_person:
                    - '15'
                    - '20'
                  gender_born_other_person:
                    - 男
                  gender_other_person:
                    - どちらでもない
                    - 男
                  boddies_other_person:
                    - 男性的
                    - ぽっちゃり
                  personalities_other_person:
                    - 優しい
                    - インドア
                  show_swipe: true
                  show_info: true
                  private_profile: true
                  activity: true
                  push_local:
                    liked: true
                    matched: true
                    message: true
                    other_news: true
                  push_email:
                    liked: true
                    matched: true
                    message: true
                    other_news: true
                  qna:
                    - question: 質問内容が入ります。
                      answer: 質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。
                    - question: 質問内容が入ります。
                      answer: 質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。
                    - question: 質問内容が入ります。
                      answer: 質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。
                    - question: 質問内容が入ります。
                      answer: 質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。質問の回答が入ります。
                  company_profile: 会社概要が入ります。会社概要が入ります。会社概要が入ります。会社h概要が入ります。会社概要が入ります。
                  terms_of_service: string
                  privacy_policy: プライバシーポリシーが入ります。プライバシーポリシーが入ります。プライバシーポリシーが入ります。プライバシーポリシーが入ります。プライバシーポリシーが入ります。プライバシーポリシーが入ります。プライバシーポリシーが入ります。プライバシーポリシーが入ります。
                  specified_commercial: 特定商取引法に基づく表示が入ります。特定商取引法に基づく表示が入ります。特定商取引法に基づく表示が入ります。特定商取引法に基づく表示が入ります。
              example-2:
                value:
                  phone: string
                  last_name: string
                  last_time_active: string
                  nick_name: string
                  has_free_time: true
                  birthday: string
                  area: string
                  city: string
                  gender_born: string
                  gender: string
                  bodies:
                    - string
                  personalities:
                    - string
                  hobbies:
                    - string
                  images:
                    - string
                  introduction: string
                  areas_other_person:
                    - area: string
                      cities:
                        - string
                  ages_other_person:
                    - string
                  gender_borns_other_person: string
                  genders_other_person: string
                  bodies_other_person: string
                  personalities_other_person:
                    - string
                  show_swipe: true
                  show_info: true
                  private_profile: true
                  activity: true
                  push_local:
                    liked: true
                    matched: true
                    message: true
                    other_news: true
                  push_mail:
                    liked: true
                    matched: true
                    message: true
                    other_news: true
                  email: string
    parameters: []
  /login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            examples:
              login:
                value:
                  email: string
                  password: string
        description: ''
  /verify/email:
    post:
      summary: ''
      operationId: post-register-verify
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
        description: ''
    parameters: []
  /verify/phone:
    parameters: []
    post:
      summary: ''
      operationId: post-verify-phone
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
  /verify/otp:
    post:
      summary: ''
      operationId: post-verify-otp
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  description: |
                    User gui ma otp gom 6 so len server xac thuc
  /user/has-time-free:
    parameters: []
    put:
      summary: ''
      operationId: put-user-has-time-free
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                has_free_time:
                  type: boolean
            examples: {}
  /user/images:
    put:
      summary: ''
      operationId: put-user-images
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
                    format: binary
  /user/introduction:
    put:
      summary: ''
      operationId: put-user-introduction
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                introduction:
                  type: string
  /user/hobbies:
    put:
      summary: ''
      operationId: put-user-hobbies
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hobbies:
                  type: array
                  items:
                    type: string
  /user/gender:
    put:
      summary: ''
      operationId: put-user-gender
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gender:
                  type: string
  /user/boddies:
    put:
      summary: ''
      operationId: put-user-boddies
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bodies:
                  type: array
                  items:
                    type: string
  /user/personalities:
    put:
      summary: ''
      operationId: put-user-personalities
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                personalities:
                  type: array
                  items:
                    type: string
  /user/schedules:
    put:
      summary: ''
      operationId: put-user-schedules
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                convenient_schedule:
                  type: array
                  items:
                    type: string
                isPublic:
                  type: boolean
  /user/job:
    put:
      summary: ''
      operationId: put-user-job
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                job:
                  type: string
                isPublic:
                  type: boolean
  /user/degree:
    put:
      summary: ''
      operationId: put-user-degree
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                degree:
                  type: string
                isPublic:
                  type: boolean
  /user/purpose-use-app:
    put:
      summary: ''
      operationId: put-user-purpose-use-app
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                purpose_use_app:
                  type: array
                  items:
                    type: string
  /user/phone:
    put:
      summary: ''
      operationId: put-user-phone
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
  /user/email:
    put:
      summary: ''
      operationId: put-user-email
      responses:
        '200':
          description: OK
        '204':
          description: Accepted
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
  /user-other/areas:
    put:
      summary: ''
      operationId: put-user-other-areas
      responses:
        '200':
          description: OK
        '204':
          description: Fail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                area:
                  type: string
                cities:
                  type: array
                  items:
                    type: string
  /user-other/ages:
    put:
      summary: ''
      operationId: put-user-other-ages
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ages:
                  type: array
                  items:
                    type: string
        description: ''
  /user-other/gender-borns:
    parameters: []
    put:
      summary: ''
      operationId: put-user-other-gender-borns
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gender_borns:
                  type: array
                  items:
                    type: string
  /user-other/genders:
    put:
      summary: ''
      operationId: put-user-other-genders
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                genders:
                  type: array
                  items:
                    type: string
        description: ''
  /user-other/bodies:
    put:
      summary: ''
      operationId: put-gender-born-bodies
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bodies:
                  type: array
                  items:
                    type: string
    parameters: []
  /user-other/personalities:
    put:
      summary: ''
      operationId: put-user-other-personalities
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                personalities:
                  type: array
                  items:
                    type: string
        description: ''
  /user/display-swipe:
    put:
      summary: ''
      operationId: put-user-display-swipe
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                display_swipe:
                  type: boolean
        description: ''
  /user/private-profile:
    put:
      summary: ''
      operationId: put-user-private-profile
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                private_profile:
                  type: boolean
  /user/show-active:
    put:
      summary: ''
      operationId: put-user-show-active
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                activity:
                  type: boolean
  /user/push-local/liked:
    put:
      summary: ''
      operationId: put-user-push-local-liked
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                liked:
                  type: boolean
        description: ''
  /user/push-local/matched:
    put:
      summary: ''
      operationId: put-user-push-local-matched
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                matched:
                  type: boolean
  /user/push-local/message:
    put:
      summary: ''
      operationId: put-user-push-local-message
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: boolean
  /user/push-local/other-news:
    put:
      summary: ''
      operationId: put-user-push-local-other-news
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                other_news:
                  type: boolean
  /user/push-mail/matched:
    put:
      summary: ''
      operationId: put-user-push-mail-matched
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                matched:
                  type: boolean
  /user/push-mail/message:
    put:
      summary: ''
      operationId: put-user-push-mail-message
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: boolean
  /user/push-mail/other-news:
    put:
      summary: ''
      operationId: put-user-push-mail-other-news
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                other-news:
                  type: boolean
  /user/push-mail/liked:
    put:
      summary: ''
      operationId: put-user-push-mail-liked
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                liked:
                  type: boolean
  /info-app:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-settings
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                qna:
                  type: object
                  properties:
                    question:
                      type: string
                    answer:
                      type: string
                terms_of_service:
                  type: string
                specified_commercial:
                  type: string
                company_profile:
                  type: string
        description: ''
    parameters: []
  /setup/areas:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-setup-areas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                areas:
                  type: array
                  items:
                    type: string
  /setup/cities:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-setup-cities
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cities:
                  type: array
                  items:
                    type: string
  /setup/gender-borns:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-setup-gender-borns
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gender_born:
                  type: array
                  items:
                    type: string
  /setup/genders:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-setup-genders
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                genders:
                  type: array
                  items:
                    type: string
  /setup/bodies:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-setup-bodies
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bodies:
                  type: array
                  items:
                    type: string
  /setup/personalities:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-setup-personalities
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                personalities:
                  type: array
                  items:
                    type: string
  /setup/hobbies:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-setup-hobbies
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hobbies:
                  type: array
                  items:
                    type: string
  /setup/ages:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-setup-ages
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ages:
                  type: array
                  items:
                    type: string
  /friends/loved:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-friends-loved
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                users:
                  $ref: '#/components/schemas/User'
            examples: {}
  /friends/matched:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-friends-matched
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                users:
                  $ref: '#/components/schemas/User'
            examples: {}
  /user/areas:
    put:
      summary: ''
      operationId: put-user-area
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                area:
                  type: string
                city:
                  type: string
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        images:
          type: array
          items:
            type: string
        last_name:
          type: string
        first_name:
          type: string
        last_active_time:
          type: string
        activity:
          type: boolean
        introduction:
          type: string
        hobbies:
          type: array
          items:
            type: string
        gender_born:
          type: string
        gender:
          type: string
        bodies:
          type: array
          items:
            type: string
        personalities:
          type: array
          items:
            type: string
        area:
          type: string
        city:
          type: string
        schedules:
          type: array
          items:
            type: string
        job:
          type: string
        degree:
          type: string
        purpose_use_app:
          type: array
          items:
            type: string
      description: Hiển thị thông tin những user khác để mình match
    Profile:
      title: Profile
      type: object
      properties:
        images:
          type: array
          items:
            type: string
        introduction:
          type: string
        last_name:
          type: string
        first_name:
          type: string
        nick_name:
          type: string
        hobbies:
          type: array
          items:
            type: string
        age:
          type: integer
        gender_born:
          type: string
        gender:
          type: string
        bodies:
          type: array
          items:
            type: string
        personalities:
          type: array
          items:
            type: string
        area:
          type: string
        city:
          type: string
        schedule:
          $ref: '#/components/schemas/Schedule'
        job:
          $ref: '#/components/schemas/Job'
        degree:
          type: string
        purpose_use_app:
          type: array
          items:
            type: string
        phone_number:
          type: string
        email:
          type: string
        areas_other_person:
          $ref: '#/components/schemas/Areas'
        ages_other_person:
          type: array
          items:
            type: string
        genders_other_person:
          type: array
          items:
            type: string
        gender_borns_other_person:
          type: array
          items:
            type: string
        bodies_other_person:
          type: array
          items:
            type: string
        personalities_other_person:
          type: array
          items:
            type: string
        profile_private:
          type: boolean
        show_swipe:
          type: boolean
        activity:
          type: boolean
        push_local:
          $ref: '#/components/schemas/PushNotification'
        push_mail:
          $ref: '#/components/schemas/PushNotification'
    PushNotification:
      title: PushNotification
      type: object
      properties:
        liked:
          type: boolean
        matched:
          type: boolean
        message:
          type: boolean
        other_news:
          type: boolean
    Job:
      title: Job
      type: object
      properties:
        job:
          type: string
        is_public:
          type: boolean
    Schedule:
      title: Schedule
      type: object
      x-examples: {}
      properties:
        DayOfWeek:
          type: string
        PartOfDay:
          type: array
          items:
            type: string
    Areas:
      title: Areas
      type: object
      properties:
        area:
          type: string
        cities:
          type: array
          items:
            type: string
